### ISSUE TITLE
Rp/Rs priors are not being written to AAVSO text file

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#1073]
#PRIORS=Period=2.15000825 +/- 1e-07,a/R*=5.344 +/- 0.039,inc=88.98 +/- 0.76,ecc=0.16,u0=2.117 +/- 0.02,u1=-3.807 +/- 0.081,u2=4.27 +/- 0.11,u3=-1.582 +/- 0.045
#PRIORS-XC={"Period": {"value": "2.15000825", "uncertainty": "1e-07", "units": "days"}, "a/R*": {"value": "5.344", "uncertainty": "0.039"}, "inc": {"value": "88.98", "uncertainty": "0.76", "units": "degrees"}, "ecc": {"value": "0.16", "uncertainty": null}, "u0": {"value": "2.117", "uncertainty": "0.02"}, "u1": {"value": "-3.807", "uncertainty": "0.081"}, "u2": {"value": "4.27", "uncertainty": "0.11"}, "u3": {"value": "-1.582", "uncertainty": "0.045"}}

no transit depth anywhere in the priors :(

**Comment by tamimfatahi** [comment]
Completed in PR #1079
