### ISSUE TITLE
Site lat/long/elevation alternate fits keys

### ISSUE THREAD

**Issue by gasilvis** [rzellem/EXOTIC#1085]
Add to the list of fits keys to examine:
SITELAT        41 43 00
SITELONG    -70 38 00
     and accept sexagesimal  
SITEELEV       3.0
These are the keys generated by MaximDL
thx
George

**Comment by tamimfatahi** [comment]
Alternative FITS keys have been added. Conversion from sexagesimal exists, reference [here].(https://github.com/rzellem/EXOTIC/blob/ac642cd2906832f7cd4f1a8fea545627e164e457/exotic/utils.py#L265)
