### ISSUE TITLE
Tweak AAVSO MD5 to make John happy

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#1095]
if epw_md5:
                f.write(f"#EPW_MD5-XC={dumps({'epw_obs_id': epw_md5})}\n")
from John Engelke to Everyone:    10:54  AM
{"epw_checkout_md5": "<md5_checksum>"}

@jpl-jengelke

**Comment by tamimfatahi** [comment]
@jpl-jengelke @rzellem This is resolved in [output_files.py](https://github.com/rzellem/EXOTIC/blob/155ab2322d6c9366c54bce92ddc99d39b700c937/exotic/output_files.py#L119). However, for TESS observations, it isn't [isn't](https://github.com/rzellem/EXOTIC/blob/main/exotic/api/output_aavso.py). Not sure if it's a requirement there or not, though. If not, please close the issue.

**Comment by jpl-jengelke** [comment]
@tamimfatahi This should only be required if the checksum exists in the data set file. For the checked out data sets from the DCS, the checksum should be included. Then it should be included in the AAVSO file. I am not sure if any TESS datasets are included in DCS checkouts. (I don't think so but I could be wrong.)

**Comment by tamimfatahi** [comment]
Yeah you're right. TESS data is scraped off ExoFOP, which means it won't have the checksum. Closing as it is complete. Thanks @jpl-jengelke!
