### ISSUE TITLE
Ultranest lockup during sampling

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#1127]
Ultranest locks up during sampling in certain rare instances when the sampler pushes up against edge of bounds. This requirement causes CITISENS to lock up on certain ephemeris calculations. 

Solution: Upgrade Ultranest from 3.3.3 to 3.5.7.

**Comment by tamimfatahi** [comment]
Closing due to updating to the latest Ultranest update 3.6.2.
