### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#1130]
Hello! I hope this is the right channel - I was setting up EXOTIC and found a broken link in the https://github.com/rzellem/EXOTIC#new-userswhere it says https://exoplanets.nasa.gov/exoplanet-watch/how-to-contribute/how-to-reduce-your-data/. Just wanted to bring it up!

**Comment by tamimfatahi** [comment]
That link does, in fact, not work. However, I think we may need to revamp the entire README.md at some point since much of the information has changed. I'll close this issue and open up another regarding changes.
