### ISSUE TITLE
WASP-140 b NEA scrape issue

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#1132]
Searching NASA Exoplanet Archive for "WASP-140 b"...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-4065b8f486c4>](https://localhost:8080/#) in <module>
    174     targ = NASAExoplanetArchive(planet=target)
    175     #appendStepToContainer('.step_container_2','Loading planet info')
--> 176     target = targ.planet_info()[0]
    177 
    178     if not targ.resolve_name():

1 frames
[/usr/local/lib/python3.8/dist-packages/exotic/api/nea.py](https://localhost:8080/#) in _get_params(self, data)
    308                 rprs = rp / rs
    309 
--> 310         if data['pl_ratdor'] < 1 or np.isnan(data['pl_ratdor']):
    311             data['pl_ratdor'] = pow((data['pl_orbper'] / 365) ** 2, 1 / 3) / (data['st_rad'] * R_SUN.to('au')).value
    312 

TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by mikeprimm** [comment]
Pretty sure this was addressed by https://github.com/rzellem/EXOTIC/commit/eb385fc642423d47439e277c56c507592e4e9e7f (in develop branch)

**Comment by tamimfatahi** [comment]
@mikeprimm Agreed. I also double-checked locally by running and no longer got this error. I'll go ahead and close it.
