### ISSUE TITLE
Certifi error on Mac install

### ISSUE THREAD

**Issue by HannimalCrackers** [rzellem/EXOTIC#1135]
I cannot successfully install EXOTIC on a MacBook. I get the following error. I do have Certifi installed.

“INFO: Validating certificate store. ...
ERROR: Incompatible or missing network security certificates. Please install and configure the 'certifi' module from PyPi. EXITING!”

This is a new MacBook running macOS Monterey v12.5, Python 3.11, certifi 2022.12.7

**Comment by tamimfatahi** [comment]
Any updates regarding this? If you are still getting this error, please let us know, and we'll reopen the issue to solve it with you. Apologies for being dormant about this.
