### ISSUE TITLE
GUI segmentation fault on Mac when browsing for file

### ISSUE THREAD

**Issue by jslash1-abc** [rzellem/EXOTIC#1148]
Hello.  When browsing for a file in the GUI, I continue to get a segmentation fault: 11 zsh -c "exotic-gui".  I'm running Monterey 12.6.3 and Python 3.10.9.

**Comment by rzellem** [comment]
This is unfortunately an issue with the Python version you're using. I've found that it will work on Python 3.8.10, but anything newer it crashes.

I also recommend you use the Colab version of EXOTIC instead- that way you don't run into these issues at all: https://exoplanets.nasa.gov/exoplanet-watch/exotic/welcome/

**Comment by jslash1-abc** [comment]
Thank you!  I appreciate the fast response.  I've started use the Colab version and it works very well . . . super recommendation.
