### ISSUE TITLE
Python segfault on macOS

### ISSUE THREAD

**Issue by JasonInRVA** [rzellem/EXOTIC#1154]
When the user clicks the "Browse Folder" button in the GUI, a segmentation fault occurs.

Configuration:

- Computer: iMac M1, 2021
- OS: macOS 13.2.1 (22D68)
- Python version: Python 3.9.16
- EXOTIC version: 2.7.0

Steps to reproduce:

1) Configure system as above.
2) Download and uncompress EXOTIC 2.7.0.
3) Double click "run_exotic_mac.command".
4) Click "Next" on the "Welcome to EXOTIC!" window.
5) Select "Complete Reduction" and click "Next".
6) Select "Analyze your image files" and click "Next".
7) Select "Manually" and click "Next".
8) Click "Browse Folder".
9) Observe that a segmentation fault occurs.

Crash logs and screenshot [here](https://www.dropbox.com/t/QhSe2TGlMFT9zRlK).

**Comment by rzellem** [comment]
This fails on newer versions of Python, unfortunately. The way to fix it is to use Python 3.8.10 or older versions.

Unclear why this fails as we're using a Python package that is supposedly natively supported. 🤷

**Comment by rzellem** [comment]
HI @JasonInRVA - I'm not sure why this is failing on your machine but it works on my Mac with Python 3.8.10.

Can you please open a terminal and type in:
`pip freeze`
and post the output here?

**Comment by JasonInRVA** [comment]
Here you go:
```
jasonsewell@Jasons-iMac-1297 ~ % pip freeze
asteval==0.9.29
astroalign==2.4.1
astropy==5.2.1
astroquery==0.4.6
barycorrpy==0.4.4
beautifulsoup4==4.11.2
bleach==6.0.0
bokeh==2.4.3
certifi==2022.12.7
charset-normalizer==3.0.1
colorcet==3.0.1
contourpy==1.0.7
corner==2.2.1
cycler==0.11.0
Cython==0.29.33
emcee==3.1.4
exotic==2.7.0
fonttools==4.38.0
future==0.18.3
holoviews==1.15.4
html5lib==1.1
idna==3.4
imageio==2.25.1
importlib-metadata==6.0.0
importlib-resources==5.10.2
jaraco.classes==3.2.3
Jinja2==3.1.2
jplephem==2.18
keyring==23.13.1
kiwisolver==1.4.4
LDTk==1.8.3
llvmlite==0.39.1
lmfit==1.1.0
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib==3.7.0
more-itertools==9.0.0
networkx==3.0
numba==0.56.4
numpy==1.23.5
packaging==23.0
pandas==1.5.3
panel==0.13.1
param==1.12.3
photutils==1.6.0
Pillow==9.4.0
pyct==0.5.0
pyerfa==2.0.0.1
pylightcurve==4.0.1
pyparsing==3.0.9
python-dateutil==2.8.2
python-version==0.0.2
pytz==2022.7.1
pyviz-comms==2.2.1
pyvo==1.4
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.2
scikit-image==0.19.3
scipy==1.10.0
semantic-version==2.10.0
sep==1.2.1
six==1.16.0
soupsieve==2.4
tenacity==8.2.1
tifffile==2023.2.3
tornado==6.2
tqdm==4.64.1
traitlets==5.9.0
typing_extensions==4.4.0
ultranest==3.5.7
uncertainties==3.1.7
urllib3==1.26.14
webencodings==0.5.1
zipp==3.13.0
```

**Comment by StefanBrezinski** [comment]
I've had the same issue with Exotic on my M1 Mac.
Solution is: Python 3.8.10 will work, but you'll have to use the INTEL version (which will run on M1, too) and you'll have to reset the libraries that came with a previously installed Python version, like this:

- Uninstall e.g. Phyton 3.11 and the libraries this way: https://www.educative.io/answers/how-to-uninstall-python
- Get the "Python 3.8.10 macOS 64bit Intel installer: https://www.python.org/downloads/release/python-3810/ 
- Install Python, after that click on file: Install Certificates.command
- Run Exotic again

**Comment by jpl-jengelke** [comment]
@JasonInRVA @StefanBrezinski Thank you for the bug report. This helped immensely.

This was diagnosed as related to #1155 when launching the regular app from the GUI failed inconspicuously. This has since been repaired with an AstroPy release.
