### ISSUE TITLE
Have variable check print name and coordinates of variable star found to ease debugging

### ISSUE THREAD

**Issue by DrDanZZ** [rzellem/EXOTIC#1164]
Right now the error message when a comp star is found to be a variable star by VSX search just says that the comp is variable. It can be a bit confusing which comp is being referred to. To help debugging it would be useful to know which variable star was found. It is a bit awkward as the vsx_variable function just returns a boolean. This bit of code change may work

 def vsx_variable(ra, dec, radius=0.01, maglimit=14):
    try:
        # check stars
        url = f"https://www.aavso.org/vsx/index.php?view=api.list&ra={ra}&dec={dec}&radius={radius}&tomag={maglimit}&format=json"
        result = requests.get(url)
        var = result.json()['VSXObjects']['VSXObject'][0]['Category']

        if var.lower() == "variable":
	    vname = result.json()['VSXObjects']['VSXObject'][0]['Name']
	    vdec = result.json()['VSXObjects']['VSXObject'][0]['Declination2000']
	    vra = result.json()['VSXObjects']['VSXObject'][0] ['RA2000']
	    log.info("\nVSX variable check found " + vname + " at  RA " + vra + ", DEC " + vdec)
            return True
        return False
    except Exception:
        return False

**Comment by tamimfatahi** [comment]
Completed in PR #1238
