### ISSUE TITLE
Support EXPOSURE in FITS header

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#1178]
One user has "EXPOSURE" for the exposure time. Looks like they have basically everything else. Need to support the following FITS header if possible:

SIMPLE  =                    T / C# FITS: 05/10/2023 19:00:48                   
BITPIX  =                    8                                                  
NAXIS   =                    2 / Dimensionality                                 
NAXIS1  =                 1280                                                  
NAXIS2  =                  960                                                  
EXTEND  =                    T / Extensions are permitted                       
BSCALE  =   1.0000000000000000 /                                                
SWCREATE= 'SharpCap'           / v3.2.5986.0, 32 bit                            
DATE-OBS= '2023-05-10T19:00:48.2243843' / System Clock:Frame Received           
GAIN    =                  360 /                                                
BLKLEVEL=                    1 /                                                
INSTRUME= 'DMx 41AU02.AS'      /                                                
INPUTFMT= 'FITS    ' /          Format of file from which image was read        
SWMODIFY= 'MaxIm DL Version 5.23 121231 1Q4E8' /Name of software that modified  
         the image                                                              
HISTORY  Dark Subtraction (Dark 1, 1280 x 960, Bin1 x 1)                        
CALSTAT = 'D       '                                                            
PEDESTAL=                 -100 /Correction to add for zero-based ADU            
EXPOSURE=   16.000000000000000 /Exposure time in seconds                        
CSTRETCH= 'Medium  ' /          Initial display stretch mode                    
CBLACK  =                  114 /Initial display black level in ADUs             
CWHITE  =                  117 /Initial display white level in ADUs             
SWOWNER = 'Mohammad Odeh' /     Licensed owner of software                      
BZERO   =  0.00000000000000000 /physical = BZERO + BSCALE*array_value           
END

**Comment by tamimfatahi** [comment]
It looks like this may have been solved in the past as [this](https://github.com/rzellem/EXOTIC/blob/155ab2322d6c9366c54bce92ddc99d39b700c937/exotic/exotic.py#L228) change is live on the main branch currently.
