### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tamimfatahi** [rzellem/EXOTIC#1218]
Much has changed over the past year or so regarding EXOTIC and updates to links to the Exoplanet Watch website. Let's see if we can refresh our GitHub repo to match those changes.

**Comment by jpl-jengelke** [comment]
Please mention the importance of entering filter data accurately. There are a number of data sets with specific wavelengths that are tied to AAVSO filter standards that are marked with a generic name code, "CV". Of course, we get data from other applications, as well as EXOTIC, so entering information correctly ensures that the correct filter is detected. The prioritization of detection is listed here: https://github.com/rzellem/EXOTIC/blob/main/exotic/api/ld.py#L79

**Comment by jpl-jengelke** [comment]
Closing this as resolved.
