### ISSUE TITLE
Fix EXOTIC's Memory Leak When Loading FITS Files

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#122]
EXOTIC seems to have a memory leak. Despite opening/closing FITS files properly, it will crash when a user has a lot of FITS files or large ones. We have to figure out how to solve this issue somehow.

**Comment by jpl-jengelke** [comment]
There is [this consideration](https://docs.astropy.org/en/stable/io/fits/#working-with-large-files), and it could well be a major culprit. **NOTE:**  See the warning! 

To deal with that consideration I would force the `hdul` object out of scope before the next loop iteration. Add a pass at the end of the loop (~ line 1680). Before the `pass`, add a `del hdul[0].data` and then follow that up with a `del hdul` or `hdul=None` (may be marginally faster) to force finalizing and garbage collecting the `FITS` object from memory entirely. My guess is that `astropy.io.fits` isn't handling memory management efficiently, so it's incumbent upon the application to do it that way.

**Comment by jpl-jengelke** [comment]
In line 1661, `hdul = fits.open(fileName)` there is the option of trying `hdul = fits.open(name=fileName, memmap=False, cache=False, lazy_load_hdus=False)` which will turn off some features that cache or do lazy loading of `FITS` files. You could try setting `memmap=False` and `lazy_load_hdus=True` to see how that affects things.

**Comment by jpl-jengelke** [comment]
Also, do we have a data set that can reproduce this?

**Comment by rzellem** [comment]
Testing on Spitzer data right now (12k images).

**Comment by rzellem** [comment]
So, this did work fine on my Spitzer data...before it used to crash in a similar manner to the others who have posted bugs on #data-reduction. Will test again without these fixes suggested by @jpl-jengelke and confirm that it does "normally" crash. If it does, then that indicates that @jpl-jengelke 's fixes worked and will make a new pull request with these changes in EXOTIC.

**Comment by rzellem** [comment]
And after 10474 images, I get the following error message:

OSError: [Errno 24] Too many open files

That implies that @jpl-jengelke 's fix works nicely! Will make a new push request to fix this issue soon.

**Comment by rzellem** [comment]
Pulled into `develop`.
