### ISSUE TITLE
Fix link in Beginner Tutorial

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#1232]
https://colab.research.google.com/drive/1Xxx7XAwgRhtV7VmxpE1Jsb3SUumsZjWR#scrollTo=pFsC9Sq61sCd

[Try using EXOTIC with observation data from an Exoplanet Watch telescope](https://colab.research.google.com/drive/1bN5SUOF76cDl63qERjnmoscxILPBW7LT)

**Comment by tamimfatahi** [comment]
Link is fixed. Closing
