### ISSUE TITLE
Problem installing EXOTIC on Mac

### ISSUE THREAD

**Issue by km8317** [rzellem/EXOTIC#1245]
Trying to install EXOTIC on Mac, Ventura 13.6.4, but won't finish loading.  Python installed without problems. Here is screen shot of error message:

<img width="641" alt="Screenshot 2024-02-18 at 9 49 44 AM" src="https://github.com/rzellem/EXOTIC/assets/160413660/11025d4e-3e7f-4cc9-91ae-de2ff527f572">

Suggestions?
Ken

**Comment by tamimfatahi** [comment]
@km8317 So sorry for the late response. Do you happen to be having any issues installing EXOTIC locally still?

**Comment by km8317** [comment]
I actually ran a transit with the update last night on Windows.  I gave up on the Mac when the Windows worked just fine.   It downloaded all the new file updates and ran normally.  What was different is that it said I was missing certain data, if I remember right, to compute radial velocities.  But, that was on my Windows computer.   Sent from my iPhoneOn Oct 16, 2024, at 12:16 AM, Tamim Fatahi ***@***.***> wrote:﻿
@km8317 So sorry for the late response. Do you happen to be having any issues installing EXOTIC locally still?

**Comment by ivenzor** [comment]
@km8317 , if this is helpful, a few months ago I wrote a small guide for local installations. You can find it on pages 50-51 of the [Exoplanet Watch Observer Manual](https://docs.google.com/document/d/1KrGKRElbA8VG98quocr6QRUeLtKtrjW4pgX8o1BXDjw/edit?usp=sharing)

**Comment by rzellem** [comment]
@km8317 - please post any issues you get with running on a Mac on our #exotic channel on our Slack! We should hopefully be able to help you out there.

**Comment by tamimfatahi** [comment]
@km8317 Any progress being made hopefully? Please let us know

**Comment by km8317** [comment]
Just ran the update and it works!!  Problem solved.  Thanks for all your help everyone.  Ken Sent from my iPhoneOn Oct 24, 2024, at 8:57 PM, Tamim Fatahi ***@***.***> wrote:﻿
@km8317 Any progress being made hopefully? Please let us know

**Comment by tamimfatahi** [comment]
Nice! Thank you @ivenzor!
