### ISSUE TITLE
Radial Velocity Input

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#1252]
Code to aggregate RV data from various sources

**Comment by sdcorle1** [comment]
@pearsonkyle  Kyle, I followed the instructions that you provided and believe that I was successful in copying three files: rvmapper.py and rvfitter_elca.py into exotic/api, then grv_fitter_notebook_for_HAT-P-23.ipynb into exotic/examples. Can you let me know if this was successful?

**Comment by jpl-jengelke** [comment]
@pearsonkyle @sdcorle1 What is the status of this?

**Comment by jpl-jengelke** [comment]
Duplicate. Closing in favor of issue #1281.
