### ISSUE TITLE
pandas.Series.bool is deprecated since Pandas 2.1.0

### ISSUE THREAD

**Issue by IraLeeBell** [rzellem/EXOTIC#1254]
Please see the following pandas document: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.bool.html

We currently use the following code in nea.py:

`if nans[k].bool():  # if col value is nan`

Need to update to the following for the above example:

`if nans[k].iloc[0]:`

...

Just creating this issue for now and will update/fix after I have a look to see if we're using the Series.bool anywhere else.

**Comment by IraLeeBell** [comment]
If anyone should tackle this before I get to it, please make sure to update the requirements.txt to a modern version of Pandas, such as 2.2.2. Ping me in Slack w/ any questions.

**Comment by ivenzor** [comment]
@IraLeeBell  It seems this is the only part of the code base where pandas.Series.bool is used. Would you like to replace _if nans[k].bool()_ with _if nans[k].any()_ instead of _if nans[k].iloc[0]:_  ?
