### ISSUE TITLE
Add RV scripts for joint fit

### ISSUE THREAD

**Issue by sdcorle1** [rzellem/EXOTIC#1281]
Notebooks for creating rv flat files from 6 high resolution rv sites and for reading those flat files into a joint fit notebook.

**Comment by jpl-jengelke** [comment]
How does this relate to #1252 ? Duplicate? Extension?

**Comment by sdcorle1** [comment]
Replacement. 1252 was corrupted through unthoughtful manipulations.

**Comment by jpl-jengelke** [comment]
Closing this as complete.
