### ISSUE TITLE
Check User Inputs

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#13]
Move planetary system parameters into the init.txt file. Have EXOTIC then check these values against the NASA Exoplanet Archive and raise an exception if they do not match. If the user does not supply them, then proceed as usual by scraping them from the Archive automatically and then asking user for agreement.

Also double check that the x,y pixel coordinates of the target star agree with the plate solution of the image.

**Comment by tamimfatahi** [comment]
I can check the x,y pixel coordinates of the target star on this issue. I can tag team this

**Comment by tamimfatahi** [comment]
Completed in pull request #128
