### ISSUE TITLE
Convert PNGs to FITS

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#131]
Some users might only be able to record their data in PNG or JPG format. However, these images *should* still have EXIF data in their headers. Therefore it *should* hopefully be straightforward to convert them to FITS files to keep EXOTIC happy. Or alternatively, we just tweak EXOTIC to be able to also read in PNG or JPG files.

**Comment by pearsonkyle** [comment]
@mjs2369 can you post a sample image?

**Comment by pearsonkyle** [comment]
Some code to accompany the image translation 

```python
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from astropy.io import fits 
from datetime import datetime

im = Image.open("2020-07-15-0312_5-CapObj_0000.PNG")
print(im.info)
data = np.array(im)
plt.imshow(data.sum(2),vmin=0,vmax=50,cmap='binary_r'); plt.colorbar(); plt.show()

gray = data.sum(2)
plt.hist(gray.flatten(), bins=np.linspace(1,256,25)); plt.ylim([0,50]); plt.show()

# save to fits file
im.info['TIME'] = datetime.now().strftime("%H:%M:%S.%f")
header = fits.Header( im.info )
hdu = fits.PrimaryHDU(gray,header=header)
hdul = fits.HDUList([hdu])
hdul.writeto("test.fits")
```

We may want to try a few tests with variable exposure times. The image below is a sum of the RGB channels

![](https://i.imgur.com/LAxqjxI.png)
