### ISSUE TITLE
Fix Error when NOT Platesolving

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#144]
`Traceback (most recent call last): // File “EXOTIC/exotic.py”, line 2149 in <module> // elif “PIXSCALE” in hdul[0].header: // NameError: name ‘hdul’ is not defined.`

**Comment by tamimfatahi** [comment]
Found the fix, just need the file to test it now.

**Comment by tamimfatahi** [comment]
Completed in pull request #145
