### ISSUE TITLE
How often do we scrape the NASA Exoplanet Archive?

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#149]
I believe we download the entire archive to a reference file locally to our own machines. Then EXOTIC queries this file to look up planets and their parameters. I believe @tamimfatahi also hard-coded this archive file to be updated monthly.

Is there any reason to not update it weekly or daily?

Also, we need to put in a `Thinking |` message to the user to let them know that this download can sometimes take some time.

**Comment by tamimfatahi** [comment]
It's updated weekly as of right now

**Comment by tamimfatahi** [comment]
First, need to contact NEA to see how often they update it and match it within EXOTIC.

**Comment by tamimfatahi** [comment]
The Exoplanet Archive updates its' holdings on a roughly 2 week basis, although this can vary in either direction to account for circumstances. We do not update on less than a weekly basis though.  - NEA
Issue closed and moved to #156
