### ISSUE TITLE
Customize Swarthmore Transit Finder for Exoplanet Watch

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#152]

**Comment by jpl-jengelke** [comment]
Does this mean create a query that matches precisely what CITISENS publishes?

**Comment by rzellem** [comment]
Yes, more or less. I'm seeing that other projects are able to upload their own target lists to the Swarthmore website, allowing users to see if those targets are observable from their own location and get all of those helpful plots. There has to be a way for us to do something similar....

**Comment by jpl-jengelke** [comment]
I've been all over the Swarthmore site but couldn't find a specific mechanism to upload. I think I am missing it. May I please get a link to the functionality?

**Comment by jpl-jengelke** [comment]
Links: 
https://astro.swarthmore.edu/~jensen/ 
https://keltsurvey.org/

**Comment by pearsonkyle** [comment]
Source code for swarthmore site: https://github.com/elnjensen/Tapir

**Comment by jpl-jengelke** [comment]
After some thought, I think this can be done by composing a URL.

**Comment by rzellem** [comment]
Also, the Swarthmore folks have offered to help us out as well. I just need to also ping Anya to make sure this is ok to link to....

**Comment by tamimfatahi** [comment]
@rzellem Completed based on [Swarthmore website.](https://astro.swarthmore.edu/transits/transits.cgi)
