### ISSUE TITLE
Bestlmfit not being detected in new Elca Application

### ISSUE THREAD

**Issue by FuwaFuwaKamiSama** [rzellem/EXOTIC#177]
When attempting to do a complete reduction on pre-reduced date in EXOTIC, the program is able to read the initialization and data files just fine; however, upon attempting to start fitting a light curve to the prereduced data, EXOTIC errors out claiming that "bestlmfit is not defined". Bestlmfit depends on myfit, a fitting variable generated externally from the recent added elca.py application. More look into how the variable is generated inside elca.py may be needed to resolve this issue.

**Comment by tamimfatahi** [comment]
Already on it, adding to requirements.txt
