### ISSUE TITLE
Comp Star != Variable Star

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#19]
Using the plate solving, confirm that the user has not accidentally selected a variable star as the comparison star. Or if they do, at least raise an exception.

**Comment by rzellem** [comment]
@FuwaFuwaKamiSama - you'll need to leverage the plate solution just coded by Tamim (I am running it right now in develop and will push to master hopefully today) to look up the star with Simbad and check if it is variable or not.

**Comment by tamimfatahi** [comment]
Completed in pull request #174
