### ISSUE TITLE
QOL Improvements for prompts

### ISSUE THREAD

**Issue by scitronboy** [rzellem/EXOTIC#2]
Many of the prompts cause errors that cause the user to lose all their progress if the value they enter is in an incorrect format, for example, a float instead of an int. These could easily be fixed with some checking and some try/catch. Also, there is no way to re-enter a value if, for example, the user makes a mistake. We could make a prompt wrapper and check for a "back" command as well as incorrect values so that the user is reprompted instead of an error being thrown. Would it be ok for me to make a PR with some quality-of-life improvements like these?

**Comment by rzellem** [comment]
Of course! Thanks!
