### ISSUE TITLE
Update EXOTIC Instructions

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#20]
Need to update EXOTIC installation and use instructions and point to them on the Wiki page (or copy them there as well). Also need more instructions on how to use EXOTIC on the Google Collab.

**Comment by rzellem** [comment]
Also need to include in the instructions using the inits.txt file.

**Comment by mjs2369** [comment]
How-EXOTIC-Works needs updates to replace the section on MCMC
