### ISSUE TITLE
Improve inits.json file

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#213]
Suggestions from Kalee Tock:
Also (not critical for this release, but just putting it here so you have it for later): Scott and I met earlier this afternoon and were discussing how it would be awesome if there could be an option where you can tell EXOTIC not to ask you any questions once you start it going.  E.g. do *not* ask for permission to upload to astrometry.net (maybe put that into the inits file if you really need permission?) or whether you want EXOTIC to calculate the limb-darkening parameters, or what filter you are using and what the bandpass is if it is custom (could that be in the inits file too?) or which values you want if the ones in the inits file conflict with what gets scraped from the Nasa Exoplanet Archive.  (Example: it scraped 0.0017 when I had entered 0.00169.  I would love to have an option in the inits file where I can just say: “If there is a conflict, use my values, not the Nasa Exoplanet Archive ones.  I looked them up and the ones in the inits file are the ones I want.“)  Also, if the pixel coordinates found from the plate solution are only a pixel or two different from the ones entered by the user, then it has to be the same star, right?  Is it really necessary to ask the user whether they want to adjust the pixel coordinates, and then do a whole second plate solution?  Also, for the command line entry option, would it be possible to ask one question about the Nasa Exoplanet Archive parameters rather than so many separate ones?  That way, the user could blanket-authorize the scraped values rather than having to examine them one by one, which is especially tedious if you are running the same system multiple times.  (Perhaps if the user says no to the blanket authorization, then the system could ask one by one.)
4:10
(Maybe there could be a “professional version” for people who know things like how to calculate limb-darkening parameters, and an “amateur version” for people who just get confused by all that.  :slightly_smiling_face:  )

**Comment by tamimfatahi** [comment]
in fact, it might be even better to have the user enter everything as a single dictionary without even separating the categories.  Then the inits.json file could basically just be a set of key-value pairs in any order, where each key represents something that the user anticipates that EXOTIC will need.  (EXOTIC could always sort them into separate dictionaries internally if that is necessary for some reason.)  For any needed key that does not appear in the inits file, EXOTIC could ask the corresponding question.  That way, the order of the inits file doesn’t matter at all: the inits file is basically just a set of things the user knows EXOTIC needs.  There could even be extra things in there that EXOTIC doesn’t care about now, but might later, or similar.
-Kalee Tock

**Comment by tamimfatahi** [comment]
It may be useful to separate the inputs, e.g. user preferences, observation location, AAVSO code, camera type, etc are less likely to change from data set to data set while star coords, filter, and planetary parameters are particular to the observation. However, the data could be structured this way by the UI and then sent to the exotic engine as one flat simple list of inputs.
-Adam Landefeld

**Comment by tamimfatahi** [comment]
Perhaps an easy way to transition from the current approach is to create two dictionaries similar to infoDist and userpDict with the corresponding key strings as they appear in the json. You could use that to look up values in json by key and not have to propagate key changes throughout the code.
-Adam Landefeld

**Comment by tamimfatahi** [comment]
Ok, but how would the user know if the values are properly retrieved, before deciding? Yes, the user must have done his/her homework by checking NASA's db before; but an extra information screen to validate would not do any harm.
-Julio Vannini

**Comment by tamimfatahi** [comment]
ah, I see.  In general, it seems like the purpose of the inits file should be to avoid mid-run questions.  So if it is possible, it would be great to give the user the option of including pixel scale (or anything else that EXOTIC might ask about) for purposes of being able to let EXOTIC run without babysitting.  If the user does not include a needed value (and opts out of the plate solution) and EXOTIC cannot find it in the fits header, then EXOTIC would ask, and the user would know that next time, if s/he wants to be able to walk away while EXOTIC is running, then that value would need to be included in the inits file.

Maybe a special section for “Things you might get asked about” so that the user knows that they need not be filled in.  Then it could be a thing where you try it once, and if you get the question, then you know that with the way you are running it and your particular images, you should include it.
-Kalee Tock

**Comment by tamimfatahi** [comment]
so maybe we just make sure that all prompts in EXOTIC can be “overridden” by the inits.json file so that a user can just run EXOTIC (after updating their inits.json file appropriately)
-Rob Zellem

**Comment by jpl-jengelke** [comment]
What about the best of both worlds? ... A flag `--yes` or `-y` to accept all requests. Or, something else, like `--quiet` or `-q` to not prompt. https://docs.python.org/3/library/argparse.html

**Comment by tamimfatahi** [comment]
a. When entering values < 1 include leading '0' eg. 0.23456 as opposed to .23456. Otherwise will through error.
	b. Wasn't obvious what date to use. Recommend stating date should be UTC (as that is what AAVSO expects)
	c. Would help to clarify or handle all Archive vs input entries the same in regards to 1) no entry, 2) 'Null' and 3) '0'. I believe there was only one entry where it was explicitly stated what to enter. And of course Null <> 0.
