### ISSUE TITLE
PSF aperture photometry/centroiding instead?

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#242]
EXOTIC is getting confused by the nearby M dwarf star to HD 189733 b in Scott Dixon's dataset...maybe need to use PSF fitting instead?

**Comment by pearsonkyle** [comment]
We estimate the centroid from the PSF and it's jumping around. I'll try to decrease the size of the prior to prevent that jump, otherwise we'll have to fit 2 PSFs

**Comment by pearsonkyle** [comment]
duplicate: https://github.com/rzellem/EXOTIC/issues/132
