### ISSUE TITLE
NEA scrapes older data (sometimes)

### ISSUE THREAD

**Issue by tamimfatahi** [rzellem/EXOTIC#248]
Seems like the NEA chooses to scrape older data for certain exoplanets (Ex: HD 189733 b). Need to fix this to take most recent data.

**Comment by pearsonkyle** [comment]
@rzellem  The transit parameters are now filled in from the most recent publications as opposed to the default value selected from NEA. 

https://github.com/rzellem/EXOTIC/pull/254/files
