### ISSUE TITLE
Bypass NEA if Unresponsive

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#269]
<img width="1575" alt="Screen Shot 2020-08-20 at 4 27 21 PM" src="https://user-images.githubusercontent.com/13021111/90836601-abcdff80-e304-11ea-9961-40471428612a.png">

Option to let the user to bypass the NASA Exoplanet Archive query if the Archive is for some reason unresponsive.

Need to make sure you post a warning message for the user to proceed at their own risk.

**Comment by pearsonkyle** [comment]
track issue here: https://github.com/rzellem/EXOTIC/tree/issue269
