### ISSUE TITLE
User input of RA at command line not working.

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#29]
From EXOTIC user: "When inputting the Dec for the target star, the program isn't recognizing that I've placed a + in front of the coordinates, and I'm unable to move forward in the process.  I've attached a screenshot for you to look at.
On my first attempt I had forgotten to type the +.
On the second attempt I did type the +, but it returned an error message that I had forgotten it.
On the third attempt, I tried putting a space between the + and the number 46.
On the fourth & fifth attempts, I tried using different + keys, one from at the top of the keyboard and the other from over on the number pad, to see if that would make a difference.  It didn't."

![Screenshot of EXOTIC](https://user-images.githubusercontent.com/13021111/84700769-a28d7480-af08-11ea-9188-d16bba860069.png)

**Comment by tamimfatahi** [comment]
Looks like it was commented out for the time being starting at line 1467 to deal with formatting. It will work for now if entered correctly the first time, but not the following.

**Comment by pearsonkyle** [comment]
Hey, I have an update for this with my API issue. We will now get the RA and DEC from the NASA exoplanet archive after the user inputs the target name and it can be found

**Comment by tamimfatahi** [comment]
Closed due to Kyle scraping off values from NEA with recent API update in pull request #42
