### ISSUE TITLE
Add more interactivity for WCS plate solutions

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#32]
1. check if the image has WCS info in the header already

2. if yes, then ask if they want to trust the WCS info

3. if no (either they do not have WCS info or they do not want to trust the WCS info), ask the user if they want to use astrometry.net

4. if yes, then proceed as usual

5. if no, then make sure you have a boolean that triggers to skip the parts of all of the following code that uses the WCS info

**Comment by tamimfatahi** [comment]
Completed in Pull Requests #71
