### ISSUE TITLE
Astrometry.net Timeout / Local Copy

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#322]
Let's say someone decides to activate a local astrometry.net to avoid downtime like yesterday. Is there a way to tell EXOTIC to look for it instead of the online version? Perhaps a .conf parameter "local_plate_resolution = true|false" and "local_astrometry_net_path" set to look for online plate resolving by default.

Also, sometimes astrometry.net can be down and EXOTIC will ping it for many minutes...maybe have it change so that if it cannot ping it after trying for 2-5 minutes, it moves on with its life?

**Comment by tamimfatahi** [comment]
Completed part 2 in pull request #335
