### ISSUE TITLE
Add Telescope Info to AAVSO Output File

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#329]
something new to add to the AAVSO output file - telescope information - e.g., name of the observatory, telescope size

**Comment by gasilvis** [comment]
Not sure what you are looking for here.
When the user submits an exo transit to the AAVSO they select a Site and an Equipment profile that they have prepared in advance that describes where and with what they made the observation. The details of those profiles are included in the zip package when you download that observation from the AAVSO website. The file is called  nnnnnnn_SiteEquipment.txt and looks like:
Site report

Site name:                                  MicroObservatory Whipple
Latitude (deg):                             31.68
Longitude (deg, west is minus):             -110.88
Altitude (m):                               1268.0
info updated:                               2020-07-25 06:59:15


Equipment report

Equipment name:                             MicroObservatory Cecilia
Observing Type:                             CCD
Telescope/Binoculars:                       MIcroObservatory
Aperture (mm):                              152
Focal Length (mm):                          560
Camera:                                     KAF-1402ME
Gain (e/ADU):                               None
Readout Noise (e):                          None
Dark Current (e/pixel/sec):                 None
Linearity Threshold (ADU):                  None
CCD Detector Pixel Count (width):           650
CCD Detector Pixel Count (height):          500
CCD Detector Pixel Width (microns):         6.8
CCD Detector Pixel Height (microns):        6.8
Filters (comma separated list):             CV
Spectrograph:                               
Type:                                       grating
Wavelength, lower limit (angstroms):        None
Wavelength, upper limit (angstroms):        None
Resolving Power (R):                        None
info updated:                               2020-04-21 10:14:11

Happy to help with any questions about the AAVSO website.

**Comment by tamimfatahi** [comment]
Will be moving to CITISENS for scraping equipment information.
