### ISSUE TITLE
Add CBB filter to the standard list for limb darkening computation

### ISSUE THREAD

**Issue by gasilvis** [rzellem/EXOTIC#337]
The specs for the CBB filter are at:
https://astrodon.com/products/astrodon-exo-planet-filter/

Bandpass looks to be 500 - 1000+

**Comment by tamimfatahi** [comment]
Should it be standard? It looks like on AAVSO it mentions that it can differ by camera. If not, should I let the FWHM be 500nm-1000nm?

**Comment by rzellem** [comment]
@gasilvis ^^^

**Comment by tamimfatahi** [comment]
Completed in pull request #348
