### ISSUE TITLE
Use FWHM for aperture and sky annulus estimations

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#339]
@pearsonkyle : "We test for 3 different annulus sizes but maybe those should be tweaked based on the FWHM rather than being a hard coded set of numbers"

**Comment by rzellem** [comment]
Can we close this issue now, @pearsonkyle ?

**Comment by pearsonkyle** [comment]
Our annulus positions are offset based on the aperture radius. The aperture radius is defined by the FWHM so yes
