### ISSUE TITLE
Add RA and DEC of best comp star to AAVSO output file

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#341]
For the output file, we should track the position of the comp star for variable star tracking, but the way to do that that would be helpful ultimately on our end is with that star’s RA and DEC position.

**Comment by tamimfatahi** [comment]
@rzellem How should this appear in the output file for AAVSO?

**Comment by jpl-jengelke** [comment]
They go into the header metadata, Here is an example of the metadata fields:
```
#TYPE=EXOPLANET
#OBSCODE=AKV
#SOFTWARE=AstroImageJ
#DELIM=,
#DATE_TYPE=BJD_TDB
#OBSTYPE=CCD
#STAR_NAME=WASP-52
#EXOPLANET_NAME=WASP-52b
#BINNING=2x2
#EXPOSURE_TIME=90
#FILTER=R
#DETREND_PARAMETERS=
#MEASUREMENT_TYPE=Rnflux
#SECONDARY_OBSCODES=
#PRIORS=P (d)=1.7497798, Teff (K)=5000, Rsun=0.815, LD u1=0.52749864, LD u2=0.0.179, [Fe/H]=0.03, log(g)=4.582
#RESULTS=(Rp/R*)^2=0.024721, a/R*=7.4445, i (deg)=85.5875, b=0.573, t14 (d)=0.075689, Rp (Rjup)=1.25
#NOTES=
```
I believe Rob will have a preference for field to insert these.

**Comment by rzellem** [comment]
@tamimfatahi - I would ping George Silvis - he is on our Slack channel and would have a good idea of where we could put this information - it might go into the "NOTES" section, but let's see what he recommends

**Comment by tamimfatahi** [comment]
Thank you both! I'll let George know about it and get back to you guys.
