### ISSUE TITLE
Continue improvements concerning expected input in prompts

### ISSUE THREAD

**Issue by Simcheck** [rzellem/EXOTIC#342]
Lots of progress already from Input changes #55 and QOL Improvements.
Consider the following:
1. Recommend **all** prompts either validate entry outright or give example of expected format in prompt i.e.
                     'Enter metallicity: e.g. 4.21, 0.21' <- here indicating leading zeros are necessary
2. Treat (accept) upper case, lower case, capitalization all the same i.e. null, NULL, Null
3. Expressly differentiate when 0, Null or blank are expected as valid entry
4. Allow for file path entries with spaces in naming. Particularly helpful for those running Linux on WSL with normal Windows file structure.

**Comment by mjs2369** [comment]
Points 2, 3 completed by Tamim.

**Comment by tamimfatahi** [comment]
@mjs2369 1 and 2 are complete, my apologies for the mixup.
