### ISSUE TITLE
Qatar-1b image NaN issues

### ISSUE THREAD

**Issue by kaleetock** [rzellem/EXOTIC#353]
To reproduce this error:

1) Go to: 
   https://drive.google.com/drive/folders/1iUsC3HA9tk2a6Ew2hUanZ4atAMqIOcuP?usp=sharing 

2) Click "Add Shortcut to Drive"

3) Go to: 
   https://drive.google.com/file/d/1tWoMhIWcaQZ91uhUSiPHYQsajJIA1ph2/view?usp=sharing 

4) Click "Add Shortcut to Drive"

5) Go to: 
     https://colab.research.google.com/drive/1px6Z0X1DPMnaUh1kZ2qKyVNZIls13Ti9?usp=sharing

6) Run each cell in sequence, authorizing the code to read files from your drive.  

The inits file is stored at "/drive/content/My Drive/inits.json".

**Comment by mfitzasp** [comment]
Is this to do with nan values in the image? If so, I have a bit of code that will interpolate nan values from surrounding pixels.

**Comment by rzellem** [comment]
@mfitzasp - it might... @pearsonkyle thought he fixed that error, but he needs to do some digging first- I'll have him reach out to you for the code if needed. Thanks so much, @mfitzasp !

**Comment by pearsonkyle** [comment]
The photometry is fine in this case. The error was in estimating mid-transit and its bounds 

Here's what it looks like: 
![Screen Shot 2020-09-23 at 3 41 08 PM](https://user-images.githubusercontent.com/4556546/94079331-58434b80-fdb3-11ea-91f4-31329bc4ebe3.png)

will push a fix soon
https://github.com/rzellem/EXOTIC/tree/issue353
