### ISSUE TITLE
Array needs to be degraded in order to use mode for the background

### ISSUE THREAD

**Issue by mfitzasp** [rzellem/EXOTIC#360]
To get the mode for the background, you need to de-float the data

rather than

dat.flatten()

you should make it truncate to one decimal place so that the histogram is well-sampled for the mode. If the data is integer this will have not effect, but if the data is float, it will reduce the number of decimal places to be suitable to estimate the mode to sufficient accuracy (0.1 counts).

mode(np.around(dat, decimals=1).flatten(), nan_policy='omit').mode[0]

https://github.com/rzellem/EXOTIC/blob/497e950990d950e2f65ffecb678c716725c84e54/exotic/exotic.py#L1489

**Comment by pearsonkyle** [comment]
Closing because we added this in
