### ISSUE TITLE
Make a GUI for EXOTIC

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#37]
Make a GUI for EXOTIC

**Comment by tamimfatahi** [comment]
Probably be best to add this towards the end of summer since EXOTIC is going through rapid changes that would require possible changes to the GUI which can be time-consuming with every update.

**Comment by pearsonkyle** [comment]
A file dialog box: 
```python
import tkinter.filedialog

tkinter.filedialog.askopenfilename()
```
Could have the user select an image and then we get the directory of all the images

**Comment by rzellem** [comment]
Switching from a tkinter GUI to a Jupiter Notebook.

**Comment by pearsonkyle** [comment]
resolved in pr: https://github.com/rzellem/EXOTIC/pull/422
https://colab.research.google.com/drive/1W1vrgEp9_IjEN16WFxmopLDYvHeYfxpw?usp=sharing
