### ISSUE TITLE
Move all user inputs to the inits file

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#373]
Right now, most of the prompts are also moved to the inits file, but the user must still:

1. select `2-1-2`
2. point to their inits file
3. confirm that they want to review the NEA scraped parameters or override them with their own

Rather, it would be nice to move these 3 prompts into the inits.json file as well so that if they are defined (i.e., not `null`), then EXOTIC will not ask the user how they want the code to be run

Then, it would be nice to be able to call EXOTIC like this:
`python exotic/exotic inits.json`
that way EXOTIC will fully run automatically **without** any user interaction at all

**Comment by tamimfatahi** [comment]
Also, add in option of cosmic ray filter.
