### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#39]

**Comment by jpl-jengelke** [comment]
This is a serious convention in Git. I wouldn't do it, at least not immediately. Various things just might not work. Consider that it could result in serious data loss if there are mistakes and/or corruptions. 

On the other hand, GitHub is working on a proposal to switch all branches on new repositories to be named 'main'. If it could wait for them, and for the tooling that uses this convention to catch up, it would be safe then.

**Comment by rzellem** [comment]
Too late! Already done!!! :)

**Comment by jpl-jengelke** [comment]
OK, I have a backup from late yesterday in case something goes wrong.
