### ISSUE TITLE
Revisit Original Photometric Extraction

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#392]
@pearsonkyle  you should look at the github history and look for a commit by @mjs2369  to change the plot from black to gray points - that should help you find this earlier version of the photometry. It also might be the very first photometric extraction method that we started with. You should definitely take a look and make sure EXOTIC is still currently using that as an option for extracting the flux.

**Comment by rzellem** [comment]
Martin Fowler  < 1 minute ago
@Kalee Tock @Rob Zellem This is consistent with my observations of the poor performance of the current EXOTIC photometry with MObs targets >12 mag (see above) ... Qatar-1 is ~12.8 mag.

**Comment by pearsonkyle** [comment]
the issue is with the image alignment interpolating the images

3 runs of exotic with/without image alignment each: 
```
*********************************************
Best Comparison Star: None
Minimum Residual Scatter: 1.4366%
Optimal Aperture: 3
Optimal Annulus: 15
********************************************
*********************************************
Best Comparison Star: None
Minimum Residual Scatter: 1.4502%
Optimal Aperture: 3
Optimal Annulus: 15
********************************************
*********************************************
Best Comparison Star: None
Minimum Residual Scatter: 1.3975%
Optimal Aperture: 3
Optimal Annulus: 15
********************************************
----------------------------- without image alignment below -----------------
*********************************************
Best Comparison Star: #5
Minimum Residual Scatter: 0.8726%
Optimal Aperture: 3
Optimal Annulus: 15
********************************************
*********************************************
Best Comparison Star: #5
Minimum Residual Scatter: 0.8726%
Optimal Aperture: 3
Optimal Annulus: 15
********************************************
*********************************************
Best Comparison Star: #5
Minimum Residual Scatter: 0.8726%
Optimal Aperture: 3
Optimal Annulus: 15
********************************************
```

The photometric results are variable with alignment. The extraction is stable otherwise. 

The order of operations in the code will have to change: 
```
for every image:
    prior = align_image()

*for every image:*
    *for every comp star:*
        *centroid = fit_centroid(prior)*

for every comp star:
    for every aperture:
        for every annulus:
            for every image:
                aper_phot(centroid[...])
            fit_lightcurve()
```

In the past, centroid fitting was performed for every aperture and annulus. Removing it from the quadruple for loop will speed things up. It will now be placed in a separate for loop prior to conducting photometry
