### ISSUE TITLE
Remove annulus selection + Increase Aperture selection

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#40]
Add a wider range of apertures based on the PSF width in the first image (Radius~2-5 sigma should be sufficient at increments of 0.1 or 0.25 pixels)

Currently, annulus sizes are varied to estimate the background flux but this can be done with a fixed annulus size and by masking out pixels brighter than the Nth (e.g. 25th) percentile as a way of automatically masking out stars within the annulus. There's no need to loop through various annulus sizes

**Comment by rzellem** [comment]
As a heads up, we used to have a more finite stepping in aperture sizes, but some users complained that EXOTIC would take *hours* to step through all of them.

We should perhaps consider doing full integer factors of the FWHM (e.g., 3-6 FWHMs?).

**Comment by pearsonkyle** [comment]
Good to know, also eliminating the double for loop should improve performance too

**Comment by rzellem** [comment]
👍

**Comment by pearsonkyle** [comment]
Closing because this was fixed a while back, we only loop through apertures now based on FWHM values from stellar PSF fit
