### ISSUE TITLE
Optimizing EXOTIC for Google Colab Users

### ISSUE THREAD

**Issue by tamimfatahi** [rzellem/EXOTIC#417]
Create a way for Google Colab users to use EXOTIC by entering in url and selecting main branch when creating a new colab. Suppressing non-needed outputs would be great as well. Saved a link on Slack from Kalee to learn more about it.

**Comment by rzellem** [comment]
@tamimfatahi - can you provide a little more details- how is this different than how EXOTIC currently runs on the Collab?

**Comment by tamimfatahi** [comment]
The idea was already done!
