### ISSUE TITLE
New fields and JSON blobs in AAVSO output file

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#419]
New fields should be added to the metadata headers in the AAVSO output file. The goal is to add some machine-parseable `JSON` while maintaining the current spec.

- `PRIORS-XC`: A one-line JSON object (not surrounded by quotes) that itemizes priors in the standard `CITISENS` value output format.
- `RESULTS-XC`: A one-line JSON object (not surrounded by quotes) that itemizes results in the standard `CITISENS` value output format.
- `COMPSTARS-XC`: A one-line JSON object (not surrounded by quotes) that itemizes compstars and related data in a format very similar to the `CITISENS` value output format.

@pearsonkyle can provide more data on the `standard CITISENS` value output format.

**NOTE:** `XC` means interchange as these fields are based on the [JSON Data Interchange Standard](https://www.json.org/json-en.html). An addendum to the name is necessary to differentiate from the original parameters.

**Comment by jpl-jengelke** [comment]
No quotes around the JSON, please.

**Comment by tamimfatahi** [comment]
Order will not matter, correct?

**Comment by jpl-jengelke** [comment]
Correct

**Comment by tamimfatahi** [comment]
Also, if a user opts to not use a plate solution and therefore we cannot get the ra & dec, it's allowable to fill in just the comparison stars? I'm assuming so due to this example:

`#COMPS={ "comps": [{ "name": 120, "ra": 12.34242, "dec": 44.23424, "x": 234, "y": 543, "fwhm": 2.3 }, { "name": 125, "ra": 12.34255, "dec": 44.23824, "x": 244, "y": 543, "fwhm": 2.1 }, { "name": 126, "ra": 12.3443, "dec": 44.2394, "x": 254, "y": 543 }] }`

where `fwhm` sometimes is not there. 

Also, would something like this be allowable in this update or would modifications need to be made in CITISENS:

`#FILTER={ "C": [400, 500]}`

**Comment by rzellem** [comment]
Yep- I would give people the option to manually fill in the RA+DEC if they do not do a plate solution.

**Comment by jpl-jengelke** [comment]
For uniformity, please try to publish values in the following format: 
```
{
	"Period": {
		"value": "2.1500082",
		"uncertainty": "1.3e-07"
	},
	"a/R*": {
		"value": "5.344",
		"uncertainty": ""
	}
}
```

... which can be condensed to ...

```
{"Period":{"value":"2.1500082","uncertainty":"1.3e-07"},"a/R*":{"value":"5.344","uncertainty":""}}
```

**Comment by jpl-jengelke** [comment]
To maintain backwards compatibility, please keep copies of the existing `FILTER`, `PRIORS`, and `RESULTS` fields with the same data in the previous format. The reason for this is to not break existing programs. We don't know who may be using AAVSO uploads, so the probability of breaking something is greater than zero. For instance, it would break `CITISENS` pipeline. Additionally, it could possibly break data validation during upload into the AAVSO DB. These fields can be removed at a later date when we verify that they are not (or no longer) being used. If they are put into a function, they can be turned off easily. 

For new fields, just go with the `-XC` field only since keeping an old style format is not critical when there is no possibility they were previously being used.
