### ISSUE TITLE
API library interleaves user inputs rendering it volatile

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#428]
The API library for LDNL (`EXOTIC/exotic/api/gaelLDNL.py`) which is meant to be imported to other applications for processing purposes includes 17 `user_input` clauses.  This stops code execution when a branch condition occurs that does not have needed parameters. 

Ideally, all UI inputs will be gathered from a main method in the master application and then the API library is invoked solely for processing. This is a structural design concern to support object oriented reuse cases.

Some UI inputs are commented `# Temporarily added`. The input requirements do not exist in releases before `0.22.0`.

**Comment by jpl-jengelke** [comment]
Example error (`WASP-39 b`) from invoking application (`CITISENS`): 
```
Please enter in the filter type (EX: Johnson V, V, STB, RJ):
```
If the filter is not specified but required then the target can either be skipped, a good default added or a best-guess made so that a processing function can be cleanly invoked by a calling method.

**Comment by tamimfatahi** [comment]
Re-routed the first part of this issue as I agree with only calling `gaelLDNL.py` when using as a tool. 

In regards to the filters, that depends on @rzellem. For `EXOTIC`, we ask the user for the filter and if it doesn't exist within the default list in the `LimbDarkening` class, it will either allow the user to add in a custom filter and FWHM, or enter their own LD parameters. 

For `CITISENS`, I can see that being an issue if the filter doesn't exist within the default list since there isn't really a way to "ask" the user what they want. We use to use the `V` filter as the default for `EXOTIC` at one point and if @rzellem is okay with it, I can see how to code for that. 

Please let me know if I understood this last part correctly.

**Comment by rzellem** [comment]
Isn't the filter provided at the top of the AAVSO file? How does it look if the user provides a custom filter? I.e., if someone provides a custom filter to EXOTIC, will the necessary info be provided in the AAVSO output file that allows us to reproduce their LD coifs?

**Comment by tamimfatahi** [comment]
If the filter is custom, which is set to output `N/A` in the AAVSO file, there is no FWHM to go with it and calculate the LD coefficients. Maybe that can be added to the AAVSO file, just like the RA & DEC for the comparison star we are currently doing?

**Comment by rzellem** [comment]
Yep, this info should be added to the AAVSO file most definitely. That way we don't have to default to anything and we can construct the LD coeffs correctly. Can you reach out to George Silvis and see where we should add this info so we don't crash the AAVSO DB?

**Comment by tamimfatahi** [comment]
The other edge-case would be for those who decide not to use the LDTK and enter their own coefficients. We can scrape these four coefficients from the already-existing AAVSO file. They are listed under `#PRIORS=` and include their uncertainties with variable names of `u0`, `u1`, `u2`, and `u3`. We can even do this for users who use the LDTK, but that's if you're okay with trusting that they used the correct planetary parameters and/or you don't care for the updated planetary parameters.

**Comment by rzellem** [comment]
That sounds good to me- I would prefer to calculate them ourselves if they give us the necessary wavelength info, but if that's not provided, we should fall back on the ones provided to us by the user themselves.

**Comment by tamimfatahi** [comment]
The last resort for `CITISENS` should be to use the default `CV` filter in `EXOTIC` if none of the above are given due to possible AIJ reduced data. The pathing should go: 

     1. Check for the filter name in the default list and use its FWHM.
     2. Use FWHM provided under the custom filter name. 
     3. Use LD coefficients in AAVSO file under `#PRIORS=` with variable names of `u0`, `u1`, `u2`, and `u3`.
     4. Use the standard `CV` filter and its FWHM in the default list.

**Comment by rzellem** [comment]
@tamimfatahi - can we close this issue?
