### ISSUE TITLE
Convert Lat and Long from HH:MM:SS to decimal

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#430]
If user supplies Lat and Long in HH:MM:SS format, EXOTIC will throw an error. Should have EXOTIC automatically convert.

**Comment by jpl-jengelke** [comment]
There is a function in CITISENS that does this, but I don't think I can post it here, so I'll message it in Slack.

**Comment by rzellem** [comment]
def dms_to_dd(dms_in):
    """
    Quick helper method to convert long/lat values in degree-minute-second (dms) form
    (using ':' separators) to decimal (dd) form
    :param dms_in: DMS long/lat value, colon separated
    :return float: Properly signed long/lat value in decimal float form
    """
    if dms_in is None or isinstance(dms_in, str) is False or str(dms_in).count(":") != 2:
        raise ValueError("Invalid DMS input provided for calculations. ...")
    # clean string of errant leading/trailing/internal spaces
    dms = str(dms_in).strip().replace(" ", "")
    degrees, minutes, seconds = dms.split(":")
    dec = abs(float(degrees)) + float(minutes) / 60. + float(seconds) / 3600.
    if float(degrees) < 0.:
        dec = dec * -1.
    return dec
