### ISSUE TITLE
"LDTk downloading uncached files"

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#435]
LDTk is downloading files multiple times for each target. This is a slow download, up to a minute or so. Is there a way to limit or cache this information. Downloads cost time and a lot of processing. Can we tell LDTk to get all the files that might be needed at the start of the server.

```https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name,hostname,tran_flag,pl_radj,pl_radjerr1,pl_refname,pl_ratdor,pl_ratdorerr1,pl_orbincl,pl_orbinclerr1,pl_orbper,pl_orbpererr1,pl_orbeccen,pl_orbeccenerr1,pl_orblper,pl_orblpererr1,pl_tranmid,pl_tranmiderr1,pl_tsystemref,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,st_teff,st_tefferr1,st_tefferr2,st_met,st_meterr1,st_meterr2,st_logg,st_loggerr1,st_loggerr2,st_mass,st_rad,st_raderr1,ra,dec,pl_pubdate+from+ps+where+tran_flag+=+1+and+default_flag+=+1+and+pl_name+=+'KELT-3+b'+order+by+pl_pubdate+desc&format=csv
https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name,hostname,tran_flag,pl_radj,pl_radjerr1,pl_refname,pl_ratdor,pl_ratdorerr1,pl_orbincl,pl_orbinclerr1,pl_orbper,pl_orbpererr1,pl_orbeccen,pl_orbeccenerr1,pl_orblper,pl_orblpererr1,pl_tranmid,pl_tranmiderr1,pl_tsystemref,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,st_teff,st_tefferr1,st_tefferr2,st_met,st_meterr1,st_meterr2,st_logg,st_loggerr1,st_loggerr2,st_mass,st_rad,st_raderr1,ra,dec,pl_pubdate+from+ps+where+tran_flag=1+and+pl_name+=+'KELT-3+b'+order+by+pl_pubdate+desc&format=csv
https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name,pl_tranmid,pl_tranmiderr1,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_refname+from+ps+where+tran_flag+=+1+and+pl_name+=+'KELT-3+b'+order+by+pl_pubdate+desc&format=csv
KELT-3 b -> data_set_count=1
KELT-3 b -> data_unbalanced=False
KELT-3 b -> data_column_count=4
>-- Temperature: 6518.0 +/- 123.73
>-- Metallicity: 0.04 +/- 0.08
>-- Surface Gravity: 4.15 +/- 0.09
Need to download 3 files, approximately 1.00 MB
LDTk downloading uncached files: 100%|██████████| 3/3 [00:08<00:00,  2.76s/it]
>-- LD0: 1.9687444082895014 +/- 0.045489046657867085
>-- LD1: -3.6185841969810335 +/- 0.18296903042133938
>-- LD2: 4.276344610441156 +/- 0.2374321518252866
>-- LD3: -1.626504821749624 +/- 0.09996514336740424
  rprs: 0.102780
  tmid: 2458572.773935
  ars: 5.323266
  a1: 1.011869
  a2: -0.010078
not enough measurements for ephemeris fit (1)
```

**Comment by tamimfatahi** [comment]
Hey @jpl-jengelke, is this regarding for `CITISENS` or both pipelines?

**Comment by tamimfatahi** [comment]
Also, the LDTk does save these files for later runs on planets of similar planetary parameters so that it would be quicker on the next run.

**Comment by jpl-jengelke** [comment]
This probably should be in CITISENS but it manifests via the EXOTIC import. 

Is there any way to pre-download the entire data set? Would that be senseless? It delays processing in the middle of data reductions to get cached files. I don't think it's a critical problem as it just makes another dependency.

**Comment by tamimfatahi** [comment]
I don't think it would be senseless to retrieve all the FITS files needed for calculating the limb darkening coefficients in order to speed up the `CITISENS` pipeline from constantly accessing the server and having to download the required FITS files for each reduction as that in its own will cause delays.

 Let me look into that a little more and seeing if it's feasible with the total size of combined files. 

If it is possible to download all these files, the good news is that the current API should not need any updates besides the object-oriented ones I will push.

**Comment by tamimfatahi** [comment]
Hey @jpl-jengelke, went ahead and looked more into this. If we want CITISENS to have every single FITS file of the spectra and not have to download for planets of different parameters, it will take up an estimated ~125 GB. I'm not entirely sure for the set-up of the pipeline behind the scenes, but is this something that could possibly be done?

**Comment by rzellem** [comment]
Still want @jpl-jengelke 's thoughts on this, but I think we should go for it. If we need more storage space, we can just go ahead and buy it. Harddrives are cheap.

**Comment by tamimfatahi** [comment]
@rzellem It's also quite possible we might not utilize even half of them, but I'm not sure. This is the blanket cover method so that it covers every bases.

**Comment by rzellem** [comment]
hi @tamimfatahi and @jpl-jengelke - is this issue still open or can we close it?
