### ISSUE TITLE
Incorrect figure references in How-EXOTIC-Works.pdf

### ISSUE THREAD

**Issue by LeonBew** [rzellem/EXOTIC#439]
Several "Figure" references in How-EXOTIC-WORKS.pdf are incorrect, linking to the wrong reference material on pages 3-5. 
This has been corrected in the German translation, but must also be corrected in the upcoming Spanish and Portuguese translations (and the English original).

**Comment by rzellem** [comment]
hi @mjs2369 - it looks like the wrong figures are being referenced in-text still (for example, on page 3, the text says ```While the target aperture sum gives the total
amount of light detected within the red circle, both
light from the star itself and the background light is included in that sum. In order to isolate the light from the star, a background annulus, which is the area between the red and green circles, is used to determine the average value of the background pixels (Figure 4).```, but it should be pointing to Figure 6 - can you please fix these for next week's release?
