### ISSUE TITLE
Create a new inits.json file for every reduction

### ISSUE THREAD

**Issue by tamimfatahi** [rzellem/EXOTIC#452]
Would be nice to create a new inits.json file for every run. That way it would save the parameters that user's entered in from the command line or even a previous inits.json that they possibly decided to update some/all of the planetary parameters.

**Comment by rzellem** [comment]
Why can't a user do this themselves now?

**Comment by tamimfatahi** [comment]
They can, but I thought it would be a good feature to add for EXOTIC to do it as well as a back-up. For example, when a user decides to enter their inputs into the command line and something goes wrong during the reduction, they would at least have an inits.json file saved in their temp folder so that the process can be even faster for next time. Also, if they entered something incorrectly in their original inits.json file such as wrong file paths, different planetary parameters, etc., the newly created inits.json will keep the updated info for that run.

What do you think? Is this a feature worth pursuing?

**Comment by rzellem** [comment]
Ah, so if the user selects to run EXOTIC by the command line, then it would build an inits.json file for them automatically?

**Comment by tamimfatahi** [comment]
Yes, also for users who already used an inits.json and updated it during the run (by using NEA planetary parameters instead is one example of an update).

**Comment by rzellem** [comment]
Ah that's an interesting idea. Let's revisit this though in 2021 and perhaps after launch.

**Comment by tamimfatahi** [comment]
Don't really need this anymore as the GUI is a better substitute for creating inits.json files.
