### ISSUE TITLE
Read lat/long from FITS header

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#495]
From Kalee:

```
if it would be possible to read the observatory lat / long / elevation from the image headers, that would be great.  I do this in the Colab I wrote for my students because understandiong the role of those parameters is not part of the learning goal for my intro assignment.  It was a little tricky because of image header idiosyncracies (e.g. you have to add the negative sign for MObs images, and some of the lat / long data is in strange units) but I was able to get it working.  It would be awesome if EXOTIC could do this internally.
```

**Comment by rzellem** [comment]
You can see the code for making the inits files from fits headers if you like if you make a copy of the Colab notebook and double click on the 4th cell (the code is hidden unless you double-click): https://colab.research.google.com/drive/1UcDfm3z1WnfdOpRwjCQYwDgK9Wh2cU6x?usp=sharing (edited)

**Comment by tamimfatahi** [comment]
Scrape elevation from FITS header

**Comment by rzellem** [comment]
and if elevation doesn't exist in FITS header, use API to query the interwebs (see issue #562)

**Comment by tamimfatahi** [comment]
Completed in PR #805
