### ISSUE TITLE
Update NEA API

### ISSUE THREAD

**Issue by tamimfatahi** [rzellem/EXOTIC#532]
Tasks: 

- If `0` (error) or `NaN` values are scraped, check for the next most recent publication of planetary parameters.
- If no publication of a specific parameter, prompt the user to input the results.

**Comment by rzellem** [comment]
@tamimfatahi and @pearsonkyle - can we close this issue?

**Comment by tamimfatahi** [comment]
Closing since this issue is too broad - will create new issues for specific parameters as they appear.
