### ISSUE TITLE
Prevent endless waiting at Simbad/GAIA variable star check

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#639]
Looks like Simbad and/or GAIA can be down sometimes, which can cause EXOTIC to endlessly wait when checking if the star is variable or not.

Maybe put in a while statement here that if it takes longer than ~30 seconds, EXOTIC alerts the user, but proceeds onwards.

**Comment by tamimfatahi** [comment]
Add `tenacity` to reloading Simbad/Gaia.
