### ISSUE TITLE
Add statement about missing data to website

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#662]

**Comment by jpl-jengelke** [comment]
Reasons for data not to be displayed:

  *   Airmass measurements (or another required data point) is not included in the data set. Current reductions require the inclusion of airmass measurements, though there may be future updates to regress this data.
  *   Data was evaluated functionally identical to another data set.
  *   Planet name is malformed or mistyped, or target is outside the set currently reduced by Exoplanet Watch, so the data set cannot be correlated to any known targets. Future plans include expanding the set of reducible targets.
  *   Data is malformed, or known priors are not implicitly defined, eliminating the capacity to calculate meaningful results.
  *   Other potentially unanticipated failures in reduction algorithms preventing data sets from converging cleanly using accepted algorithms.
