### ISSUE TITLE
Rename Instructions: Windows -> Windows + Linux

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#663]

**Comment by jpl-jengelke** [comment]
Just wanted to throw out some ideas: 
- Break out installation instructions into ...
  - Colab 
  - Personal Computer:
  - (Part 1) Requirements/Setup: 
    - Mac
    - Windows
  - (Part 2) Linux/Unix Terminal installation

This would entail having computer system-specific setup instructions that precede Linux/Unix Terminal instructions.

**Comment by rob** [comment]
Looks good guys. Keep it up.

@rob

**Comment by rzellem** [comment]
Just spotted a broken link from the Exotic PyPi web page described as "...additional installation instructions including setting up dependencies for Mac, Windows and Linux" pointing to a non-existent (or possibly relocated) shell script at "https://pypi.org/project/exotic/exotic_installation_linux.sh"

**Comment by jpl-jengelke** [comment]
Link was malformed. I just fixed it. However, I'm not sure that's how we want to present the Linux instructions.
