### ISSUE TITLE
Calculate pixel scale

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#67]
Some users do not know the pixel scale. However, we can directly calculate it due to the plate solution. Now recommend just automatically calculating the pixel scale after doing the plate solution and asking the user to check.

**Comment by tamimfatahi** [comment]
Tested with MOBs and is successful. Did a pull request #77 , still open for further testing.

**Comment by tamimfatahi** [comment]
Tested on LCO data. Successful.
