### ISSUE TITLE
Update EXOTIC Prompts

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#672]
1. EXOTIC asks for dir of flats for all of the cals
2. Tmid uncertainty units JD --> BJD_TDB

**Comment by tamimfatahi** [comment]
Found Error for 1., changes are on issue_670 branch. Can either do a PR for that or if you want, but this is the change:
Current:

> def check_calibration(directory, image_type):
>     if not directory:
>         opt = user_input(f"\nDo you have {image_type}? (y/n): ", type_=str, val1='y', val2='n')
>         if opt == 'y':
>             directory = user_input(f"Please enter the directory path to your Flats "
>                                    "(must be in their own separate folder): ", type_=str)
>     if directory:
>         return check_imaging_files(directory, image_type)
>     return None


Updated:
> def check_calibration(directory, image_type):
>     if not directory:
>         opt = user_input(f"\nDo you have {image_type}? (y/n): ", type_=str, val1='y', val2='n')
>         if opt == 'y':
>             directory = user_input(f"Please enter the directory path to your {image_type} "
>                                    "(must be in their own separate folder): ", type_=str)
>     if directory:
>         return check_imaging_files(directory, image_type)
>     return None

**Comment by tamimfatahi** [comment]
Regarding the newer error for slicing through plate solution file to grab comparison star coordinates:
Current:
```
if bestCompStar:
    comp_ra = None
    comp_dec = None

    if wcs_file:
        comp_ra = rafile[comp_coords[1]][comp_coords[0]]
        comp_dec = decfile[comp_coords[1]][comp_coords[0]]

    comp_star.append({
        'ra': str(comp_ra) if comp_ra else comp_ra,
        'dec': str(comp_dec) if comp_dec else comp_dec,
        'x': str(comp_coords[0]) if comp_coords[0] else comp_coords[0],
        'y': str(comp_coords[1]) if comp_coords[1] else comp_coords[1]
    })
```

Updated:
```
if bestCompStar:
    comp_ra = None
    comp_dec = None

    if wcs_file:
        comp_ra = rafile[int(comp_coords[1])][int(comp_coords[0])]
        comp_dec = decfile[int(comp_coords[1])][int(comp_coords[0])]

    comp_star.append({
        'ra': str(comp_ra) if comp_ra else comp_ra,
        'dec': str(comp_dec) if comp_dec else comp_dec,
        'x': str(comp_coords[0]) if comp_coords[0] else comp_coords[0],
        'y': str(comp_coords[1]) if comp_coords[1] else comp_coords[1]
    })
```

**Comment by tamimfatahi** [comment]
Regarding the newer error for slicing through plate solution file to grab comparison star coordinates:
Current:
```
if bestCompStar:
    comp_ra = None
    comp_dec = None

    if wcs_file:
        comp_ra = rafile[comp_coords[1]][comp_coords[0]]
        comp_dec = decfile[comp_coords[1]][comp_coords[0]]

    comp_star.append({
        'ra': str(comp_ra) if comp_ra else comp_ra,
        'dec': str(comp_dec) if comp_dec else comp_dec,
        'x': str(comp_coords[0]) if comp_coords[0] else comp_coords[0],
        'y': str(comp_coords[1]) if comp_coords[1] else comp_coords[1]
    })
```

Updated:
```
if bestCompStar:
    comp_ra = None
    comp_dec = None

    if wcs_file:
        comp_ra = rafile[int(comp_coords[1])][int(comp_coords[0])]
        comp_dec = decfile[int(comp_coords[1])][int(comp_coords[0])]

    comp_star.append({
        'ra': str(comp_ra) if comp_ra else comp_ra,
        'dec': str(comp_dec) if comp_dec else comp_dec,
        'x': str(comp_coords[0]) if comp_coords[0] else comp_coords[0],
        'y': str(comp_coords[1]) if comp_coords[1] else comp_coords[1]
    })
```
