### ISSUE TITLE
Look into NINA

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#687]
https://nighttime-imaging.eu

**Comment by LeonBew** [comment]
Espeically look into suggesting use of Nick Hardy's [new NINA plugin for exoplanets](https://bitbucket.org/NickHardy/nina/src/plugins/NINA.Plugin.ExoPlanets/). For users with their own telescope, the process of data acquisition is **significantly** reduced both in difficulty and time investment with NINA and his plugin.

Discussion and preview:
https://uol-ets.slack.com/archives/C0133SRMMPV/p1622748376007700?thread_ts=1621535943.000400&cid=C0133SRMMPV
