### ISSUE TITLE
Make executables for requirements.txt install and EXOTIC GUI launch

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#712]
@rzellem wants to be lazy and double click instead of running stuff from the Command Line.

**Comment by jpl-jengelke** [comment]
Please see https://github.com/rzellem/EXOTIC/issues/713#issuecomment-855172836

**Comment by jpl-jengelke** [comment]
POSIX error codes (hard to find): https://chromium.googlesource.com/chromiumos/docs/+/HEAD/constants/errnos.md

**Comment by rzellem** [comment]
hi @jpl-jengelke - sounds like we can now close this issue, correct?
