### ISSUE TITLE
More robust planet name filtering

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#74]
Right now, users are getting an error if they input "HAT-P-32b" instead of having a space between the host star name and the planet letter. If they input the planet name in this manner, an error is raised. Maybe have EXOTIC correct the planet name to add the space and then have EXOTIC ask the user to check the changed name.

For example:

User inputs "HAT-P-32b"
EXOTIC sees the lack of a space and says to the user:
"Did you mean HAT-P-32 b? (y/n)" or something similar
Then the user can confirm.

**Comment by pearsonkyle** [comment]
Here are some planet names to stress test: 

HD 189733 b
GJ 1214 b
CoRoT-1 b

I added a feature to the code to be case insensitive. I don't think there will ever be a planet that requires case to distinguish it self

**Comment by jpl-jengelke** [comment]
The planet identifier can be split off using the host star name. Then a space can be reintroduced. The real problems arise when spaces and dashes are moved about.

**Comment by tamimfatahi** [comment]
Completed in pull request #80
