### ISSUE TITLE
More robust limb darkening coefficient calculations

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#75]
Right now, if a user enters an AAVSO-support limb darkening coefficient that is NOT listed on the EXOFAST website (http://astroutils.astronomy.ohio-state.edu/exofast/limbdark.shtml), then an error will be raised.

Perhaps we allow the user to enter an AAVSO-supported LD coefficient. But if it is not on the EXOFAST website, we allow them to choose the appropriate one from the list...?

**Comment by pearsonkyle** [comment]
I'd say pick the closest filter from the set that is available to EXOFAST (U,B,V,R,I,J,H,K) 
If you want to get really fancy, LDTK allows one to calculate coefficients for an arbitrary filter if you know the wavelength region: https://github.com/hpparvi/ldtk

**Comment by rzellem** [comment]
Yeah we should make the jump to LDTK and calculate this ourselves. Want to assign yourself to that task and work with Tamim, Kyle?

Sent from my iPhone

On Jun 25, 2020, at 6:25 PM, Kyle A. Pearson <notifications@github.com> wrote:

﻿

I'd say pick the closest filter from the set that is available to EXOFAST (U,B,V,R,I,J,H,K)
If you want to get really fancy, LDTK allows one to calculate coefficients for an arbitrary filter if you know the wavelength region: https://github.com/hpparvi/ldtk

**Comment by tamimfatahi** [comment]
Completed in pull request #80
