### ISSUE TITLE
EXOTIC Notebook Error [Jupyter Lab]

### ISSUE THREAD

**Issue by R0b0ty** [rzellem/EXOTIC#755]
Testing with **EXOTIC 0.46.6**, obtained an error when executing the _Exotic_Notebook.ipynb_ Jupyter Lab notebook file.  It seems to be dependent on the selected target for _wcsfile_ (i.e., no issue is observed when using the default HAT-P-32 target, but when using Qatar-1, for example, an error was seen).  My thought is that (at a minimum) a more descriptive error message is needed, as it's unclear whether the user can proceed with executing the rest of the cells in the notebook.  I'm sorry that I didn't have time to look into this further.

### The following file contains my current setup...

[config_info.md](https://github.com/rzellem/EXOTIC/files/6681076/config_info.md)

### Error seen with Qatar-b:
![JupyterLab_Error](https://user-images.githubusercontent.com/3391252/122650158-510d5c00-d0ff-11eb-9b5d-dbb20368cc21.png)

### Results with default HAT-P-32 target:
![With_HAT-P-32](https://user-images.githubusercontent.com/3391252/122650161-536fb600-d0ff-11eb-860a-0a153402b1ba.png)
![fedora_linux](https://user-images.githubusercontent.com/3391252/122650163-57033d00-d0ff-11eb-94fb-318acc1a68e6.png)

**Comment by tamimfatahi** [comment]
Looks like Simbad is having a tough time finding Qatar-1 b in it's database.

**Comment by rzellem** [comment]
hi @R0b0ty - is this still an issue or has this been resolved?

**Comment by R0b0ty** [comment]
> hi @R0b0ty - is this still an issue or has this been resolved?

I haven't tried in a while, but I can this week and report back.

**Comment by rzellem** [comment]
hi @R0b0ty - is this still an issue? or has this been fixed?

**Comment by R0b0ty** [comment]
Hi, Rob.  Comparing this old _Jupyter_ notebook from EXOTIC **0.46.6** with the latest one in the current EXOTIC version, it has changed significantly such that this issue is no longer applicable.  In fact, I ran the new _Jupyter_ notebook, selected **Qatar-1 b** as the target, and the relevant data was downloaded with no issues.  I would propose closing this issue as fixed somewhere along the way, and verified with EXOTIC version 1.8.4.  My apologies for the late response.

**Comment by tamimfatahi** [comment]
Yeah, this is mostly regarding Simbad's syntax of exoplanet names rather than our end. Will close the issue.

**Comment by rzellem** [comment]
Awesome! Thanks for taking a look, @R0b0ty !
