### ISSUE TITLE
Relax NEA Query

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#765]
@LeonBew: "The NEA query is far too specific, I entered "HAT-P-3b" but it failed because it demands "HAT-P-3 b". The user's input should be recognized even without dashes or spaces. (Tamim mentioned this exists but can be extended)"

**Comment by tamimfatahi** [comment]
Looks like the NEA updated their syntax of how to query planets and might be able to do this for us. We just need to update the API again since we are now using the retired version. Will do this next.

**Comment by tamimfatahi** [comment]
Completed in PR #811
