### ISSUE TITLE
Add AAVSO comparison star suggestion within the reduction process 

### ISSUE THREAD

**Issue by LeonBew** [rzellem/EXOTIC#771]
A proper choice of comparison stars for all new users will have a positive impact on lightcurve quality. 
Either launch a browser window containing the AAVSO's VSP plot, or show the VSP plot _and table_ within the EXOTIC GUI. 

**Browser query:**

> app.aavso.org/vsp/chart/?star=`HOSTSTAR`&scale=&orientation=CCD&type=chart&fov=`USERFOV`&maglimit=16.5&resolution=150&north=down&east=right

And if the user has a filter other than V (which is the default if none is entered):

> /chart/?star=`HOSTSTAR`&scale=&orientation=CCD&type=chart&fov=`USERFOV`&maglimit=16.5&resolution=150&north=down&east=right&`USERFILTER`=on

More information including filter options [here](https://app.aavso.org/vsp/chart/). Note that the AAVSO may not have all possible targets, which is why a failure to find the target on the VSP should not give an error, but instead notify the user and prompt to select comparison stars manually. 

[Relaxing the query](https://github.com/rzellem/EXOTIC/issues/765#event-4919552015) also applies here, preferably allow the user to input "wasp14b", "wasp-14b", "wasp 14", or other variations, instead of the VSP's "WASP-14".

**Comment by rzellem** [comment]
https://app.aavso.org/vsp/
https://www.aavso.org/sites/default/files/VSP_Help.pdf

**Comment by tamimfatahi** [comment]
Completed in PR #1035
