### ISSUE TITLE
Add "pre-reduced data" feature back to EXOTIC GUI

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#783]

**Comment by rzellem** [comment]
@tamimfatahi - is this fixed back in the command line version of EXOTiC? If so, I can add it back in to the GUI.

**Comment by tamimfatahi** [comment]
@rzellem It is fixed in the command line version, however, the `inits.json` needed to be updated for a full run without keyboard input. This actually also adds the ability for `--prereduced` to also be ran without keyboard input since I updated the `inits.json` file.

**Comment by rzellem** [comment]
Just gonna tweak this a lil bit more :)
