### ISSUE TITLE
Add option to scale darks

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#814]
Make this a toggleable option and provide details so the users know what they're getting into.

Procedure: 
```
Michael Fitzgerald  2:19 PM
You take bias frames, dark frames, flat frames.
2:19
Make an average of the bias frames and subtract them from the dark frames and the flat frames
2:20
2. Make an average of the dark frames and then divide them by the exposure time giving an image in dark current per second
2:20
3. remove the dark current from the flat frames (scaled to exposure) and make a master flat frame by averaging
2:21
For a target image you subtract the average bias frame, you subtract the average dark frame * exposure time, then you divide by the average flat frame.
```

**Comment by pearsonkyle** [comment]
Michael Fitzgerald  6:06 PM
So dark scaling won't work if you can't keep your camera at a consistent temperature. The solution to that would be setting a warmer temperature.

**Comment by tamimfatahi** [comment]
Just wanted to add - I believe branch` issue_127` has some progress regarding dark scaling that has stayed idle since last summer.

**Comment by tamimfatahi** [comment]
There we mixed opinions on adding this by Leon and others. I will close the issue for now unless wanted.
