### ISSUE TITLE
Dependency tree for EXOTIC GUI overlaps launching application

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#820]
EXOTIC GUI is trying to import EXOTIC as a library before it launches the application. It is actually made to run in standalone mode to then launch the main application as the last step. The runtime is confounded and then the chain of execution is broken.

Solution: Pull the class `NASAExoplanetArchive` out of EXOTIC main and put it into the API directory. Import it separately for both EXOTIC_GUI and EXOTIC as needed. Probably some caching of any downloaded files will be helpful to prevent delays.

**Comment by jpl-jengelke** [comment]
This is related to the email sent this AM regarding the blank launch error: 
```
At the end of the install....nothing.
Following the install instructions:
https://exoplanets.nasa.gov/exoplanet-watch/how-to-contribute/how-to-reduce-your-data/
Step #4 states "After EXOTIC finishes loading, you will see a welcome screen."
Well, I don't see a welcome screen.
```

**Comment by rzellem** [comment]
Let's chat about this fix in our meeting today, @jpl-jengelke

**Comment by jpl-jengelke** [comment]
Two action items: 
- @jpl-jengelke Add cert installer to installation script
- @tamimfatahi Move `EXOTIC`'s `NASAExoplanetArchive` class into its own class file in the api directory. Import this into both `exotic_gui` and `exotic`. This decouples the GUI and EXOTIC.

**Comment by tamimfatahi** [comment]
> * @tamimfatahi Move `EXOTIC`'s `NASAExoplanetArchive` class into its own class file in the api directory. Import this into both `exotic_gui` and `exotic`. This decouples the GUI and EXOTIC.

Completed
