### ISSUE TITLE
Check for Stellar Variability Against VSX

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#856]
use AAVSO to determine if star is variable or not in addition to Simbad and GAIA

**Comment by rzellem** [comment]
Daniel's orig notebook: https://drive.google.com/file/d/16-DS5kwYZJNNB4D8AjAVv-EsbZBRGVo2/view?usp=sharing

**Comment by tamimfatahi** [comment]
Completed in PR #1035
