### ISSUE TITLE
Additional centroid estimate

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#864]
Add an option/way to conduct aperture photometry with a flux weighted centroid. 

The current code fits for a PSF and uses the center of the PSF model for aperture photometry but if the PSF is non-gaussian the model center will be biased.

**Comment by pearsonkyle** [comment]
https://drive.google.com/drive/folders/12kKEjlLI6W7tC8OmQJvtq6Fx5F5nens8

**Comment by tamimfatahi** [comment]
@pearsonkyle Completed in PR #934
