### ISSUE TITLE
HD 80606

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#870]
What is its ephemeris?
How uncertain is the duration?

**Comment by rzellem** [comment]
https://exoplanetarchive.ipac.caltech.edu/overview/HD%2080606%20b#planet_HD-80606-b_collapsible

Most recent ephemeris *and* period is:
2454424.852±0.008
111.4357±0.0008
(Pont et al. 2009)

Most recent period is:
111.43639+0.00032-0.00031
(Rosenthal et al. 2021)

Recommend to use Pont ephemeris and Rosenthal orbital period.
Next transit: ~Dec 7-8, 2022 -> 2459920.50000 JD

So, the uncertainty is (see Eqn. 4 in Zellem et al. 2020):
delta_Tmid = (n_orbit**2 * delta_P**2 + 2n_orbit*delta_P*delta_T + delta_T**2)**0.5

> where n_orbit = (2459920.50000-2454424.852)/111.43639
> n_orbit = 49.3 ~ 49

delta_Tmid = (49**2 * 0.00032**2 + 0.0008**2)**0.5
delta_Tmid = 0.0157003949 days = 22.6 minutes
