### ISSUE TITLE
Issue with custom filter

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#877]
Doug Yesterday at 4:49 PM
Issue with custom filter: Running Exotic from the GUI it allows you to enter N/A and the later asks for the max min wavelength. If you try to run it from the init file it does not notice that the wavelengths are in the file and asks for what filter. I will not accept N/A so it can query you for the wavelength.  So you are out of luck. I also notice that if you go back to a successful the run and take a look at the init. file that it generates it does not put the wavelengths in the file

**Comment by tamimfatahi** [comment]
Completed in PR #1070
