### ISSUE TITLE
Update light curve code for eccentric planets

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#893]
1) add longitude of periastron into NEA scraper
2) update light curve code. Will need to convert longitude of periastron into a time of periastron

https://github.com/rzellem/EXOTIC/blob/main/exotic/api/elca.py#L219 

light curve code only works for circular orbits currently.

**Comment by rzellem** [comment]
@pearsonkyle - can we close this issue?

**Comment by pearsonkyle** [comment]
https://github.com/rzellem/EXOTIC/pull/924
