### ISSUE TITLE
Image processing/generation error in JPL reduction pipeline

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#912]
"""
        lclabel2 = r"$T_{\emph{mid}}$ = %s $\pm$ %s BJD$_{\emph{TDB}}$" %(
            str(round_to_2(self.parameters['tmid'], self.errors.get('tmid',0))),
            str(round_to_2(self.errors.get('tmid',0)))
        )
"""
https://github.com/rzellem/EXOTIC/blob/e2c9793a4dc4c6a50562ff54b368f170ccab0ce9/exotic/api/elca.py#L386

In the pipeline, stuff like this is reported. ... 
"""
ERROR:__main__:Image generation failed to execute completely. ...
ERROR:__main__:SV status remains at 'reduced'. ...
ERROR:__main__:
T_{\emph{mid}}
   ^
Unknown symbol: \emph, found '\'  (at char 3), (line:1, col:4)
pyparsing.ParseFatalException: Unknown symbol: \emph, found '\'  (at char 3), (line:1, col:4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/_mathtext.py", line 2277, in parse
    result = self._expression.parseString(s)
"""

**Comment by jpl-jengelke** [comment]
I am going to attempt to fix this now.

**Comment by jpl-jengelke** [comment]
Could not resolve immediately. Branch issue_912 was created. @pearsonkyle please have a look if there's a moment. I am unfamiliar with all the syntax for Pyplot labels.

**Comment by jpl-jengelke** [comment]
Should `\emph` be replaced with `\textbf`?

**Comment by tamimfatahi** [comment]
Could it also be that you can use `\\emph`?

**Comment by rzellem** [comment]
Yeah adding the `\emph` was my attempt to get rid of the italics when something is subscripted- but it looks like this might be a matplotlib issue: https://github.com/pyparsing/pyparsing/issues/318

I'm going to try to use the `\textit` command instead- it should do the same thing. Will push as a bugfix and new release shortly. Stand by.
