### ISSUE TITLE
EXOTIC asks for comp stars even if listed in inits file

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#933]
Even if a comp star is listed in the inits file, EXOTIC sometimes will still ask the user:

```
How many Comparison Stars would you like to use? (1-10): 

Comparison Star 1 X Pixel Coordinate: 
Comparison Star 1 Y Pixel Coordinate: 
```

**Comment by tamimfatahi** [comment]
Could I see an example of how the user listed it or a slack link to the error? Let me know when you get the chance!

**Comment by rzellem** [comment]
Actually this hasn't popped up again...might have just been a 1-off random bug...closing issue for now.
