### ISSUE TITLE
Wrong valid datatype for Image Scale

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#939]
Not able to find Image Scale in the Image Header.
Please enter Image Scale (e.g., 5 arcsec/pixel): 5 arcsec/pixel
Sorry, not a valid datatype.
Please enter Image Scale (e.g., 5 arcsec/pixel):

**Comment by tamimfatahi** [comment]
The prompt has been changed to:
```
Please enter Image Scale (arcsec/pixel):
```
This will become crucial when checking good comp stars using API from AAVSO as it will help give an estimate for the size of FOV. Must be a float input. If you want to modify the prompt to be more clear, let me know @rzellem as I'm closing this issue.
