### ISSUE TITLE
Check Transit Duration Output

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#943]
Check that the value and its uncertainty on Transit Duration isn't accidentally flipped around.

**Comment by tamimfatahi** [comment]
@rzellem Checked this just now, looks good to me. Waiting on your approval to close, but I can link the code [here](https://github.com/rzellem/EXOTIC/blob/197d05802f58779c731058ba537b3b78c09ecbe3/exotic/exotic.py#L2383) (I also debugged it)

**Comment by rzellem** [comment]
Thanks, @tamimfatahi !

FYI - you're allowed to close issues if you'd like! :D
