### ISSUE TITLE
Browse Folder button crashes on macOS

### ISSUE THREAD

**Issue by Shad0wSeven** [rzellem/EXOTIC#947]
Whenever the "Browse Folder" button is pressed (macOS Big Sur 11.1) sometimes there will be a crash. 

![image](https://user-images.githubusercontent.com/19739712/149852146-768ab292-f871-43ca-ae56-9b96cf6cea17.png)

![image](https://user-images.githubusercontent.com/19739712/149852139-a4ed5297-e15e-4ae6-94f6-ac9379a6a43f.png)

**Comment by tanishakasar** [comment]
Hi, did you find a solution for this?

**Comment by rzellem** [comment]
hi @tanishakasar - it looks like this is an issue with Mac OS and the latest version of Python. The way I was able to fix it was by downloading Python 3.7.9, which can be downloaded here:
https://www.python.org/downloads/release/python-379/

**Comment by rzellem** [comment]
I just tested Python 3.8.10 - that seems to work as well.

**Comment by rzellem** [comment]
Python 3.10.5 still results in a segmentation fault, though

**Comment by tanishakasar** [comment]
Hi @rzellem , It's working good now - I downloaded Python 3.7.9. Thanks!

**Comment by tamimfatahi** [comment]
@rzellem I feel like this should be safe to close as it isn't our issue to fix. I can test though if it is working properly again.

**Comment by rzellem** [comment]
Agreed. Closing!
