### ISSUE TITLE
Fix Manual Planet Entry

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#96]
Right now, when the user inputs a planet name that is not on the NASA Exoplanet Archive, EXOTIC asks the user to type in "manual" - instead, @rzellem recommends that if the user types in a planet name that is not recognized in the NASA Exoplanet Archive, EXOTIC asks the user to check their spelling or to confirm that this is a planet candidate. If it is a candidate (and therefore not listed in the Archive), the user has to manually input the planetary parameters.

Otherwise, right now when the user inputs the word "manual", EXOTIC crashes.

**Comment by rzellem** [comment]
Also, when someone types "manual", EXOTIC does not like it:

![image](https://user-images.githubusercontent.com/13021111/86949220-2ea74c00-c103-11ea-947e-607ad14377e6.png)

**Comment by tamimfatahi** [comment]
Completed in pull request #91
