### ISSUE TITLE
HD 80606 argument of periastron not populating from NEA

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#962]
A user (Subham Samantaray) just ran HD 80606b with EXOTIC and had the code adopt all NEA values automatically. However, looking at the inits file, it did not write the argument of periastron to the file and looking at the data, it looks like EXOTIC thought that this value == 0, instead of its actual value.

Wonder if argument of periastron isn't properly being treated through all parts of EXOTIC.

**Comment by tamimfatahi** [comment]
Completed in PR #1004
