### ISSUE TITLE
Check for Corrupted Images

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#967]
Maybe a "try/except" to move along if an image is corrupted.

**Comment by tamimfatahi** [comment]
There is a corruption check in the code, do you happen to have an example of what file caused this?

**Comment by rzellem** [comment]
Nope- I think a user mentioned this months ago and unfortunately I completely forget.

If EXOTIC is already doing a corruption check, then please just go ahead and close this Issue, @tamimfatahi.

**Comment by tamimfatahi** [comment]
I'll reopen if this issue still persists. For now, I do have code checking for corruption. Thank you for the update!
