### ISSUE TITLE
Check *all* Paths at Beginning

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#97]
Right now, some users are finding that if they accidentally type in the, e.g., output path incorrectly, that EXOTIC will fully crash. This is particularly annoying as EXOTIC will fully run to the end and then fail just before saving all of its output.

Recommend that we check *all* directories at the very beginning of the code and then throw the user an error message if anything is wrong. That way they have the chance to fix things before they break.

**Comment by rzellem** [comment]
If the path is not correct or exists, recommend you give the user the option to make the path directly from EXOTIC.

**Comment by tamimfatahi** [comment]
Completed in pull request #91
